### ISSUE TITLE
Testes Unitários com Jest

### ISSUE THREAD

**Issue by brenofranca83** [SocialSoftwareLivingLab/docs#1]
- [ ] Caso de teste simples (sem mock, sem setup e tear down)
- [ ] Caso de teste com setup e tear down
- [ ] Caso de teste com mock(s)
- [ ] Caso de testes parametrizados (ref https://dev.to/tinesoft/be-smart-write-parameterized-tests-with-jest-3eab)

**Comment by Antonio214** [comment]
Sugestão: Vou criar um primeiro passo ensinando a como configurar o Jest num projeto do zero e além disso como preparar o VSCode para rodar em conjunto ao Jest.

**Comment by Antonio214** [comment]
Finalizado por enquanto. Vou atualizar o readme para apontar para o repositorio com o conteúdo pesquisado.
